---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_prefs: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - chromedriver
  - doxygen
  - gettext
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libdvdcss
  - libevent
  - packer
  - python
  - sqlite
  - mcrypt
  - mysql
  - nmap
  - npm
  - nvm
  - php70
  - php70-mcrypt
  - php70-xdebug
  - ssh-copy-id
  - cowsay
  - readline
  - subversion
  - openssl
  - pv
  - drush
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - fing
  - firefox
  - google-chrome
  - handbrake
  - hipchat
  - java
  - kdiff3
  - licecap
  - limechat
  - macvim
  # - menumeters
  # - yujitach-menumeters # Forked version for 10.11+ support.
  - nvalt
  - sequel-pro
  - skype
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant
  - virtualbox
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids: []
mas_email: ""
mas_password: ""
