---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
# configure_dock: true
# dockitems_remove:
#   - Launchpad
#   - TV
#   - Podcasts
#   - "App Store"

configure_dock: true
dockitems_remove:
  - Mail
  - Maps
  - Photos
  - TV
  - FaceTime
  - "App Store"
  - Reminders
  - Calendar
  - Contacts
  - Freeform
  - Notes
  - News
  - Music
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google\ Chrome.app/"
    pos: 1
  - name: "Safari"
    path: "/Applications/Safari.app"
    pos: 2
  - name: "Messages"
    path: "/Applications/Messages.app"
    pos: 3
  - name: "Discord"
    path: "/Applications/Discord.app"
    pos: 4
  - name: "Steam"
    path: "/Applications/Steam.app"
    pos: 5
  - name: "System Settings"
    path: "/Applications/System\ Settings.app"
    pos: 6

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - mas
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - tart

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - microsoft-edge
  - webex
  - firefox
  - google-chrome
  - discord
  - raspberry-pi-imager
  - steam
  - obs
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
configure_mas_apps: true
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 310633997, name: "WhatsApp" }
mas_email: ""
mas_password: ""

osx_script: "{{ playbook_dir }}/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
