---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
# https://formulae.brew.sh/analytics/install/365d/
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - mercurial
  - gpg
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - wget
  - vim
  - cmake
  - ninja

homebrew_taps:
  - homebrew/core
  - homebrew/cask
# https://formulae.brew.sh/analytics/cask-install/365d/
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - station
  - firefox
  - google-chrome
  - slack
  - sublime-text
  - zoomus
  - steam
  - brave-browser
  - meld
  - google-backup-and-sync
  - sabnzbd 
  - vlc
  - skype 
  - dropbox 
  - sabnzbd
  - ledger-live
  - spotify
  - keybase
  - resilio-sync
  - shadow
  - google-backup-and-sync
  - plex
  - plex-media-server
  - visual-studio-code
  - sourcetree
  - station
  - suspicious-package
  - grandperspective

  #- microsoft-office # tres long

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 552383089, name: "Dashlane - Password Manager" }
  - { id: 1176895641, name: "Spark - Email App by Readdle " }  
  - { id: 406056744, name: "Evernote" }  

  #- { id: 497799835, name: "xcode"} 

mas_email: ""
mas_password: ""
osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
